carts/urls.py
from django.conf.urls import url

from . import views

app_name = 'carts'
urlpatterns = [
  #url(r'^view-cart/$', views.view_cart, name='view_cart'),
  url(r'^update-cart/(?P<cartitem_id>[0-9]+)/$', views.update_cart, name='update_cart'),
  url(r'^view-cart/$', views.view_cart, name='view_cart'),
  url(r'^delete/(?P<pk>[0-9]+)/$', views.CartItemDelete.as_view(), name='cartitem_delete'),
]

ecommerce/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^items/', include('items.urls')),
    url(r'^carts/', include('carts.urls')),
    url(r'^orders/', include('orders.urls')),
    url(r'^admin/', admin.site.urls),
]

items/urls.py
from django.conf.urls import url

from . import views

app_name = 'items'
urlpatterns = [
  url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^(?P<pk>[0-9]+)/$', views.ItemDetail.as_view(), name='detail'),
]

items/models.py
from django.db import models
from django.core.validators import MinValueValidator

class Item(models.Model):
  name = models.CharField(max_length=200)
  price = models.PositiveIntegerField(validators=[MinValueValidator(0)])
  msrp = models.PositiveIntegerField(validators=[MinValueValidator(0)])
  description = models.TextField()
  
  def __str__(self):
    return self.name

class InventoryItem(models.Model):
  item = models.ForeignKey(Item, on_delete=models.CASCADE)
  qty = models.PositiveIntegerField(validators=[MinValueValidator(0)])
  
  def __str__(self):
    return '{}, Qty {}'.format(self.item.name, self.qty)

qa/models.py
from django.db import models

from items.models import Item

# Create your models here.
class Question(models.Model):
  item = models.ForeignKey(Item, on_delete=models.CASCADE)
  pub_date = models.DateTimeField('date published')
  question_content = models.CharField(max_length=128)
  votes = models.IntegerField(default=0)

  class Meta:
    ordering = ['-votes']

class Answer(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  pub_date = models.DateTimeField('date published')
  author = models.CharField(max_length=64)
  answer_content = models.TextField()
  votes = models.IntegerField(default=0)

  class Meta:
    ordering = ['-votes']

reviews/models.py
from django.db import models

from items.models import Item

# Create your models here.
class Review(models.Model):
  item = models.ForeignKey(Item, on_delete=models.CASCADE)
  pub_date = models.DateTimeField('date published')
  author = models.CharField(max_length=64)
  rating = models.IntegerField()
  votes = models.IntegerField(default=0)
  review_content = models.TextField()

  class Meta:
    ordering = ['-votes']

items/forms.py
from django import forms

from .models import InventoryItem

#TODO: rename to ItemQtyForm
class QtyForm(forms.Form):
  
  MIN_QTY = 1

  def __init__(self, *args, **kwargs):
    self.item_id = kwargs.pop('item_id', None)
    super(QtyForm, self).__init__(*args, **kwargs)
    self.fields['qty'] = forms.ChoiceField(self.find_number_choices())


  def find_number_choices(self):
    start = self.MIN_QTY
    end = self.find_max_qty()
    zipped = zip(*[range(start, end + 1)] * 2)
    return [t for t in zipped]


  def find_max_qty(self):
    inventory_item = InventoryItem.objects.filter(item_id=self.item_id).first()
    return inventory_item.qty

items/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic, View

from .models import Item
from .forms import QtyForm 
from carts.views import add_to_cart

class IndexView(generic.ListView):
  template_name = 'items/index.html'
  context_object_name = 'item_list'

  def get_queryset(self):
    return Item.objects.order_by('name')


class ItemDisplay(generic.DetailView):
  model = Item
  template_name = 'items/detail.html'

  def get_context_data(self, **kwargs):
    context = super(ItemDisplay, self).get_context_data(**kwargs)
    context['qty_form'] = QtyForm(item_id=self.get_object().id)
    return context


class ItemAdd(generic.detail.SingleObjectMixin, generic.FormView):
  template_name = 'items/detail.html'
  form_class = QtyForm
  model = Item

  def post(self, request, *args, **kwargs):
    self.object = self.get_object()
    return super(ItemAdd, self).post(request, *args, **kwargs)

  def get_form(self):
    return self.form_class(data=self.request.POST, item_id=self.object.pk)

  def get_context_data(self, **kwargs):
    context = super(ItemAdd, self).get_context_data(**kwargs)
    context['qty_form'] = context.get('form')
    return context 

  def get_success_url(self):
    add_to_cart(self.request, self.object.pk)
    return reverse('carts:view_cart')


class ItemDetail(View):

  def get(self, request, *args, **kwargs):
      view = ItemDisplay.as_view()
      return view(request, *args, **kwargs)

  def post(self, request, *args, **kwargs):
      view = ItemAdd.as_view()
      return view(request, *args, **kwargs)

items/templates/items/detail.html
<p>{% include 'items/view_items.html' %}</p>
<p>{% include 'carts/view_cart.html' %}</p>

<ul>
  <li>{{ item.name }}</li>
  <li>${{ item.price}}</li>
  <li>MSRP: ${{ item.msrp}}</li>
  <li>Description: {{ item.description}}</li>
  <li>Qty remaining: {{ item.inventoryitem_set.first.qty }}</li>
</ul>

<br>
<br>

<form action="{% url 'items:detail' item.id %}" method="post">
{% csrf_token %}
<!-- Qty: <input type="number" name="qty" /> -->
{{ qty_form }}
<input type="submit" value="Add to cart" />
</form>

<br>
<br>

<ul>
  Q and A:
  {% for question in item.question_set.all %}
    <li>
      <p>{{ question.votes }} votes Date published: {{ question.pub_date }} </p>
      <p>{{ question.question_content }}</p>
      <ul>
      {% for answer in question.answer_set.all %}
        <li>
          <p>{{ answer.votes }} votes Date published: {{ question.pub_date }}  Author: {{ answer.author }} </p>
          <p>{{ answer.answer_content }}</p>
        </li>
        <br>
      {% endfor %}
      </ul>
    </li>
    <br>
  {% endfor %}
</ul>

<br>
<br>

<ul>
  Reviews:
  {% for review in item.review_set.all %}
    <li>
      <p>{{ review.rating }} stars   Date published: {{ review.pub_date }}   Author: {{ review.author }}  {{ review.votes }} votes</p>
      <p>{{ review.review_content }}</p>
    </li>
  {% endfor %}
</ul>

items/templates/items/index.html
<p>{% include 'carts/view_cart.html' %}</p>

{% if item_list %}
    <ul>
    {% for item in item_list %}
        <li><a href="{% url 'items:detail' item.id %}">{{ item.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No items are available.</p>
{% endif %}

items/templates/items/view_items.html
<a href="{% url 'items:index' %}">Return to items</a>